-- Create Profiles table
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users(id) PRIMARY KEY,
  email TEXT, -- Nullable to support Anonymous Auth
  city TEXT,
  state TEXT,
  last_seen TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS on Profiles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own profile" 
  ON public.profiles FOR SELECT 
  USING (auth.uid() = id);

CREATE POLICY "Users can view other users' city" 
  ON public.profiles FOR SELECT 
  USING (true);

CREATE POLICY "Users can update their own profile" 
  ON public.profiles FOR UPDATE 
  USING (auth.uid() = id);

CREATE POLICY "Users can insert their own profile" 
  ON public.profiles FOR INSERT 
  WITH CHECK (auth.uid() = id);

-- Create Collections table
CREATE TABLE IF NOT EXISTS public.collections (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) NOT NULL,
  sticker_id TEXT NOT NULL,
  count INTEGER DEFAULT 0,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(user_id, sticker_id)
);

-- Enable RLS on Collections
ALTER TABLE public.collections ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own collection" 
  ON public.collections FOR SELECT 
  USING (auth.uid() = user_id);

CREATE POLICY "Users can view everyone's duplicates" 
  ON public.collections FOR SELECT 
  USING (count > 1);

CREATE POLICY "Users can update their own collection" 
  ON public.collections FOR UPDATE 
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own collection" 
  ON public.collections FOR INSERT 
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete their own collection" 
  ON public.collections FOR DELETE 
  USING (auth.uid() = user_id);
